import './globals.css';
import NavBar from "./NavBar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <span>hello</span>
        <style>{`
          a {
            color: white;
          }
        `}</style>
      </body>
    </html>
  )
}