import './globals.css';
import NavBar from "./NavBar";
import Head from 'next/head';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}